[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "binarysearch"
version = "0.1.0"
description = "Binary search algorithms and LeetCode solutions."
authors = [
    { name = "ritz-dx" }
]
readme = "README.md"
requires-python = ">=3.8"
